min_logging_level: info

hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  - hdf5_config: opendata_electrons # toy_dataset

  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

convert_config:
  ntuples_dir: /data0/jang/opendata/1LMET30 # change to your ntuple directory
  key: analysis # NOSYS/physics
  output_dir: null
  output_file: fakes.hdf5
  max_files: null
  step_size: 65536
  num_workers: -1
  n_piles: 128
  chunk_shape: 32
  multiprocessing_context: fork
  pile_assignment: random
  merge_piles: false
  njets_cut: null
  met_cut: null
  mT_cut: null
  scale_wzjets: true
  njets_cut: [1, inf]
  mT_cut: [0.0, 60.0]
  crack_veto: true
