min_logging_level: info

hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  - dataset_config: opendata_electrons
  - model_config: ratio
  - tuning_config: null
  - plotting_config: plotting_config

  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

experiment_config:
  experiment_name: opendataElectrons
  run_name: null

  save_dir: null # set to ANALYSIS_ML_LOGS_DIR if null
  tracker_path: null # set to ANALYSIS_ML_RESULTS_DIR if null

  seed: 0
  accelerator: gpu
  devices: auto
  precision: 32-true
  float32_matmul_precision: high

  log_every_n_steps: 20
  check_eval_n_epoch: 1
  num_sanity_val_steps: 0
  check_metrics_n_epoch: 1
  plot_metrics_n_epoch: 1
  tqdm_refresh_rate: 1
